name: Test EC2 SSM

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::836503213491:role/GitHubActions-Deploy-Auth
          aws-region: us-east-1

      - name: Check AWS identity
        run: |
          aws sts get-caller-identity

      - name: Run command on EC2
        run: |
          aws ssm send-command \
            --instance-ids i-01e773d973f2a1cb3 \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["echo GitHub Actions connected successfully","whoami","docker --version","docker compose version"]'